package com.devmanchego.contextextractor.render;

import com.devmanchego.contextextractor.callgraph.CallNode;
import com.devmanchego.contextextractor.java.model.EndpointInfo;
import com.devmanchego.contextextractor.matching.MatchedFlow;

import java.nio.file.Path;
import java.util.*;

/**
 * Generates a Markdown file with Mermaid {@code classDiagram} and PlantUML class diagrams
 * for each matched API flow.
 *
 * Output file naming: if main output is {@code api-spec.md}, this writes {@code api-spec-classes.md}.
 */
public final class ClassDiagramRenderer {

    public String render(List<MatchedFlow> flows,
                         Map<EndpointInfo, CallNode> callGraphs,
                         Path rootPath) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Full-Stack API Class Diagrams\n\n");
        sb.append("*Generated by java-angular-fullstack-extractor*\n\n");
        sb.append("---\n\n");

        int flowNum = 1;
        for (MatchedFlow flow : flows) {
            CallNode root = callGraphs.get(flow.getJavaEndpoint());
            if (root == null) continue;

            String method = flow.getAngularCall().getHttpVerb().name();
            String path   = flow.getJavaEndpoint().getPathTemplate();
            String title  = method + " " + path;

            sb.append("## Flow ").append(flowNum++).append(": ").append(title).append("\n\n");

            appendMermaidClassDiagram(sb, title, flow, root);
            appendPlantUmlClassDiagram(sb, title, flow, root);
            sb.append("---\n\n");
        }

        return sb.toString();
    }

    // -----------------------------------------------------------------------
    // Static path helper
    // -----------------------------------------------------------------------

    /**
     * Derives the class diagram output file path from the main output file path.
     * {@code /path/to/api-spec.md} → {@code /path/to/api-spec-classes.md}
     */
    public static Path classesOutputPath(Path mainOutputFile) {
        String name = mainOutputFile.getFileName().toString();
        String base = name.endsWith(".md") ? name.substring(0, name.length() - 3) : name;
        return mainOutputFile.resolveSibling(base + "-classes.md");
    }

    // -----------------------------------------------------------------------
    // Public PlantUML builder (for use by PNG exporter)
    // -----------------------------------------------------------------------

    public String buildPlantUmlClassSource(String title, MatchedFlow flow, CallNode root) {
        StringBuilder sb = new StringBuilder();
        sb.append("@startuml\n");
        sb.append("!pragma layout smetana\n");
        sb.append("title ").append(title).append("\n");

        List<CallNode> nodes = collectNodes(root);

        // Declare classes
        for (CallNode node : nodes) {
            String simpleName = simpleClassName(node.getClassName());
            sb.append("class ").append(quotePumlName(simpleName)).append(" {\n");
            String returnType = node.getReturnType() != null ? node.getReturnType() : "void";
            sb.append("    +").append(node.getMethodName()).append("() : ")
              .append(escPuml(returnType)).append("\n");
            sb.append("}\n");
        }

        // Declare interfaces referenced via implementedInterfaces
        Set<String> declaredInterfaces = new LinkedHashSet<>();
        for (CallNode node : nodes) {
            for (String iface : node.getImplementedInterfaces()) {
                if (declaredInterfaces.add(iface)) {
                    sb.append("interface ").append(quotePumlName(iface)).append(" {\n}\n");
                }
            }
        }

        // Relationships between consecutive nodes
        for (int i = 0; i < nodes.size() - 1; i++) {
            String from = simpleClassName(nodes.get(i).getClassName());
            String to   = simpleClassName(nodes.get(i + 1).getClassName());
            sb.append(quotePumlName(from)).append(" \"1\" -- \"1\" ").append(quotePumlName(to)).append(" : uses\n");
        }

        // Interface implementations
        for (CallNode node : nodes) {
            String simpleName = simpleClassName(node.getClassName());
            for (String iface : node.getImplementedInterfaces()) {
                sb.append(quotePumlName(simpleName)).append(" ..|> ").append(quotePumlName(iface)).append("\n");
            }
        }

        // Superclass extensions
        for (CallNode node : nodes) {
            if (node.getSuperClass() != null) {
                String simpleName = simpleClassName(node.getClassName());
                sb.append(quotePumlName(simpleName)).append(" --|> ").append(quotePumlName(node.getSuperClass())).append("\n");
            }
        }

        // DTO dependencies on controller
        if (!nodes.isEmpty()) {
            String controllerName = simpleClassName(nodes.get(0).getClassName());
            flow.getTsRequestModel().ifPresent(req ->
                sb.append(quotePumlName(controllerName)).append(" ..> ").append(quotePumlName(req.getName())).append(" : receives\n"));
            flow.getTsResponseModel().ifPresent(resp ->
                sb.append(quotePumlName(controllerName)).append(" ..> ").append(quotePumlName(resp.getName())).append(" : returns\n"));
        }

        sb.append("@enduml\n");
        return sb.toString();
    }

    // -----------------------------------------------------------------------
    // Mermaid class diagram
    // -----------------------------------------------------------------------

    private void appendMermaidClassDiagram(StringBuilder sb, String title, MatchedFlow flow, CallNode root) {
        sb.append("### Mermaid\n\n```mermaid\nclassDiagram\n");

        List<CallNode> nodes = collectNodes(root);

        // Declare classes
        for (CallNode node : nodes) {
            String simpleName = simpleClassName(node.getClassName());
            sb.append("    class ").append(quoteMermaidName(simpleName)).append(" {\n");
            String returnType = node.getReturnType() != null ? node.getReturnType() : "void";
            sb.append("        +").append(node.getMethodName()).append("() ")
              .append(escMermaid(returnType)).append("\n");
            sb.append("    }\n");
        }

        // Declare interfaces referenced via implementedInterfaces
        Set<String> declaredInterfaces = new LinkedHashSet<>();
        for (CallNode node : nodes) {
            for (String iface : node.getImplementedInterfaces()) {
                if (declaredInterfaces.add(iface)) {
                    sb.append("    class ").append(quoteMermaidName(iface)).append(" {\n");
                    sb.append("        <<interface>>\n");
                    sb.append("    }\n");
                }
            }
        }

        // Relationships between consecutive nodes
        for (int i = 0; i < nodes.size() - 1; i++) {
            String from = simpleClassName(nodes.get(i).getClassName());
            String to   = simpleClassName(nodes.get(i + 1).getClassName());
            sb.append("    ").append(quoteMermaidName(from)).append(" \"1\" --> \"1\" ").append(quoteMermaidName(to)).append(" : uses\n");
        }

        // Interface implementations
        for (CallNode node : nodes) {
            String simpleName = simpleClassName(node.getClassName());
            for (String iface : node.getImplementedInterfaces()) {
                sb.append("    ").append(quoteMermaidName(simpleName)).append(" ..|> ").append(quoteMermaidName(iface)).append("\n");
            }
        }

        // Superclass extensions
        for (CallNode node : nodes) {
            if (node.getSuperClass() != null) {
                String simpleName = simpleClassName(node.getClassName());
                sb.append("    ").append(quoteMermaidName(simpleName)).append(" --|> ").append(quoteMermaidName(node.getSuperClass())).append("\n");
            }
        }

        // DTO dependencies on controller
        if (!nodes.isEmpty()) {
            String controllerName = simpleClassName(nodes.get(0).getClassName());
            flow.getTsRequestModel().ifPresent(req ->
                sb.append("    ").append(quoteMermaidName(controllerName)).append(" ..> ").append(quoteMermaidName(req.getName())).append(" : receives\n"));
            flow.getTsResponseModel().ifPresent(resp ->
                sb.append("    ").append(quoteMermaidName(controllerName)).append(" ..> ").append(quoteMermaidName(resp.getName())).append(" : returns\n"));
        }

        sb.append("```\n\n");
    }

    // -----------------------------------------------------------------------
    // PlantUML class diagram
    // -----------------------------------------------------------------------

    private void appendPlantUmlClassDiagram(StringBuilder sb, String title, MatchedFlow flow, CallNode root) {
        sb.append("### PlantUML\n\n```plantuml\n");
        sb.append(buildPlantUmlClassSource(title, flow, root));
        sb.append("```\n\n");
    }

    // -----------------------------------------------------------------------
    // Participant collection (pre-order traversal, unique class names)
    // -----------------------------------------------------------------------

    private List<CallNode> collectNodes(CallNode root) {
        List<CallNode> result = new ArrayList<>();
        Set<String> seen = new LinkedHashSet<>();
        collectNodesPreOrder(root, result, seen);
        return result;
    }

    private void collectNodesPreOrder(CallNode node, List<CallNode> result, Set<String> seen) {
        String simpleName = simpleClassName(node.getClassName());
        if (seen.add(simpleName)) {
            result.add(node);
        }
        for (CallNode callee : node.getCallees()) {
            collectNodesPreOrder(callee, result, seen);
        }
    }

    // -----------------------------------------------------------------------
    // Escape helpers
    // -----------------------------------------------------------------------

    private String escMermaid(String s) {
        if (s == null) return "";
        return s.replace("\"", "'");
    }

    private String escPuml(String s) {
        if (s == null) return "";
        // Replace generic angle brackets with ~ (Mermaid-style) so PlantUML does not
        // interpret them as creole markup inside class-member text. Never applied to
        // arrows/structure — only to label text.
        return s.replace("<", "~").replace(">", "~").replace("\"", "'");
    }

    /** Quote class/interface names in PlantUML if they contain special characters. */
    private String quotePumlName(String name) {
        if (name == null || name.isEmpty()) return name;
        // Quote if name contains special chars: ~, <, >, :, -, [, ], etc.
        if (name.matches(".*[~<>:\\-\\[\\]~].*")) {
            return "\"" + name.replace("\"", "\\\"") + "\"";
        }
        return name;
    }

    /** Quote class/interface names in Mermaid if they contain special characters. */
    private String quoteMermaidName(String name) {
        if (name == null || name.isEmpty()) return name;
        // Quote if name contains special chars, replace quotes with single quotes
        if (name.matches(".*[~<>:\\-\\[\\]~].*")) {
            return "\"" + name.replace("\"", "'") + "\"";
        }
        return name;
    }

    private String simpleClassName(String name) {
        if (name == null) return "Unknown";
        return name.contains(".") ? name.substring(name.lastIndexOf('.') + 1) : name;
    }
}
