package com.devmanchego.contextextractor.render;

import com.devmanchego.contextextractor.callgraph.CallNode;
import com.devmanchego.contextextractor.callgraph.FlowCondition;
import com.devmanchego.contextextractor.java.model.EndpointInfo;
import com.devmanchego.contextextractor.java.model.ScheduledJobInfo;
import com.devmanchego.contextextractor.matching.MatchedFlow;

import java.nio.file.Path;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Generates a Markdown file with Mermaid and PlantUML flowcharts for each
 * matched API flow and each scheduled job.
 *
 * Output file naming: if main output is {@code api-spec.md}, this writes {@code api-spec-flows.md}.
 */
public final class FlowDiagramRenderer {

    public String render(List<MatchedFlow> flows,
                         Map<EndpointInfo, CallNode> callGraphs,
                         Map<ScheduledJobInfo, CallNode> jobCallGraphs,
                         Path rootPath) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Full-Stack API Flow Diagrams\n\n");
        sb.append("*Generated by java-angular-fullstack-extractor*\n\n");
        sb.append("---\n\n");

        int flowNum = 1;
        for (MatchedFlow flow : flows) {
            CallNode root = callGraphs.get(flow.getJavaEndpoint());
            if (root == null) continue;

            String method = flow.getAngularCall().getHttpVerb().name();
            String path   = flow.getJavaEndpoint().getPathTemplate();
            sb.append("## Flow ").append(flowNum++).append(": ")
              .append(method).append(" ").append(path).append("\n\n");

            appendMermaid(sb, method + " " + path, root);
            appendPlantUml(sb, method + " " + path, root);
            sb.append("---\n\n");
        }

        if (!jobCallGraphs.isEmpty()) {
            sb.append("## Scheduled Jobs\n\n");
            for (Map.Entry<ScheduledJobInfo, CallNode> entry : jobCallGraphs.entrySet()) {
                ScheduledJobInfo job = entry.getKey();
                CallNode root = entry.getValue();
                String simpleClassName = job.getClassName().contains(".")
                        ? job.getClassName().substring(job.getClassName().lastIndexOf('.') + 1)
                        : job.getClassName();
                String title = simpleClassName + "::" + job.getMethodName();
                sb.append("### ").append(title).append("\n\n");
                appendMermaid(sb, title, root);
                appendPlantUml(sb, title, root);
                sb.append("---\n\n");
            }
        }

        return sb.toString();
    }

    // -----------------------------------------------------------------------
    // Mermaid
    // -----------------------------------------------------------------------

    private void appendMermaid(StringBuilder sb, String title, CallNode root) {
        sb.append("### Mermaid\n\n```mermaid\ngraph TD\n");
        AtomicInteger counter = new AtomicInteger(0);
        String startId = "N" + counter.getAndIncrement();
        sb.append("    ").append(startId).append("([\"")
          .append(escMermaid(title)).append("\"])\n");
        renderMermaidNode(sb, root, startId, counter);
        sb.append("```\n\n");
    }

    /**
     * Renders a CallNode as a rectangle, followed by its conditions (diamonds),
     * then connects to callees. Returns the last node ID so the parent can chain.
     */
    private String renderMermaidNode(StringBuilder sb, CallNode node,
                                     String parentId, AtomicInteger counter) {
        String myId = "N" + counter.getAndIncrement();
        String label = buildNodeLabel(node);
        sb.append("    ").append(myId).append("[\"").append(escMermaid(label)).append("\"]\n");
        sb.append("    ").append(parentId).append(" --> ").append(myId).append("\n");

        String chainId = myId;

        chainId = renderMermaidConditions(sb, node.getConditions(), chainId, counter);

        for (CallNode callee : node.getCallees()) {
            chainId = renderMermaidNode(sb, callee, chainId, counter);
        }

        return chainId;
    }

    private String buildNodeLabel(CallNode node) {
        StringBuilder label = new StringBuilder();
        label.append("[").append(node.getRole().name()).append("] ");
        label.append(node.getClassName()).append("::").append(node.getMethodName());
        if (node.isTransactional()) label.append(" @Tx");
        if (node.getReturnType() != null) label.append(" : ").append(node.getReturnType());
        return label.toString();
    }

    private String escMermaid(String s) {
        return s.replace("\"", "'");
    }

    // -----------------------------------------------------------------------
    // PlantUML
    // -----------------------------------------------------------------------

    private void appendPlantUml(StringBuilder sb, String title, CallNode root) {
        sb.append("### PlantUML\n\n```plantuml\n");
        sb.append(buildPlantUmlSource(title, root));
        sb.append("```\n\n");
    }

    /** Builds a self-contained PlantUML activity diagram source string (without Markdown fences). */
    public String buildPlantUmlSource(String title, CallNode root) {
        StringBuilder sb = new StringBuilder();
        sb.append("@startuml\n");
        sb.append("!pragma layout smetana\n");
        sb.append("title ").append(title).append("\n");
        sb.append("start\n");
        renderPlantUmlNode(sb, root, 0);
        sb.append("stop\n@enduml\n");
        return sb.toString();
    }

    private void renderPlantUmlNode(StringBuilder sb, CallNode node, int depth) {
        String indent = "  ".repeat(depth);
        sb.append(indent).append(":")
          .append(sanitizePumlLabel(buildNodeLabel(node))).append(";\n");

        for (FlowCondition cond : node.getConditions()) {
            renderPlantUmlCondition(sb, cond, indent);
        }

        for (CallNode callee : node.getCallees()) {
            renderPlantUmlNode(sb, callee, depth);
        }
    }

    private void renderPlantUmlNodeFull(StringBuilder sb, CallNode node, int depth) {
        String indent = "  ".repeat(depth);
        sb.append(indent).append(":")
          .append(sanitizePumlLabel(buildNodeLabel(node))).append(";\n");

        for (FlowCondition cond : node.getAllConditions()) {
            renderPlantUmlCondition(sb, cond, indent);
        }

        for (CallNode callee : node.getCallees()) {
            renderPlantUmlNodeFull(sb, callee, depth);
        }
    }

    /**
     * Renders one if/else condition block.
     * When the Yes-branch throws an exception and there is no else, adds {@code kill}
     * so the diagram correctly shows that branch as a terminal — the flow after
     * {@code endif} is only reached via the implicit No path.
     */
    private void renderPlantUmlCondition(StringBuilder sb, FlowCondition cond, String indent) {
        sb.append(indent).append("if (").append(escPuml(cond.getConditionText()))
          .append("?) then (Yes)\n");

        boolean thenThrows = cond.getThenSummary() != null
                && cond.getThenSummary().startsWith("throws");

        if (cond.getThenSummary() != null) {
            sb.append(indent).append("  :").append(escPuml(cond.getThenSummary())).append(";\n");
        }
        if (thenThrows && !cond.isHasElse()) {
            sb.append(indent).append("  kill\n");
        }

        if (cond.isHasElse()) {
            sb.append(indent).append("else (No)\n");
            if (cond.getElseSummary() != null) {
                sb.append(indent).append("  :").append(escPuml(cond.getElseSummary())).append(";\n");
            }
        }
        sb.append(indent).append("endif\n");
    }

    private String escPuml(String s) {
        if (s == null || s.isEmpty()) return "\"\"";
        // Also neutralize angle brackets: with no global sanitization at export time,
        // raw < > in labels would be parsed as creole markup by PlantUML.
        String escaped = s.replace("\"", "\\\"").replace("<", "~").replace(">", "~");
        return "\"" + escaped + "\"";
    }

    /** Neutralizes characters that break PlantUML activity labels (:label;). */
    private String sanitizePumlLabel(String s) {
        if (s == null) return "";
        return s.replace("<", "~").replace(">", "~").replace(";", ",");
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private String truncate(String s, int max) {
        return s.length() <= max ? s : s.substring(0, max - 3) + "...";
    }

    /**
     * Renders an unfiltered version: includes ALL top-level if/else conditions
     * (loops still excluded). Uses {@link CallNode#getAllConditions()} instead of
     * {@link CallNode#getConditions()}.
     */
    public String renderFull(List<MatchedFlow> flows,
                             Map<EndpointInfo, CallNode> callGraphs,
                             Map<ScheduledJobInfo, CallNode> jobCallGraphs,
                             Path rootPath) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Full-Stack API Flow Diagrams (All Conditions)\n\n");
        sb.append("*Generated by java-angular-fullstack-extractor — unfiltered: all top-level if/else conditions included.*\n\n");
        sb.append("---\n\n");

        int flowNum = 1;
        for (MatchedFlow flow : flows) {
            CallNode root = callGraphs.get(flow.getJavaEndpoint());
            if (root == null) continue;

            String method = flow.getAngularCall().getHttpVerb().name();
            String path   = flow.getJavaEndpoint().getPathTemplate();
            sb.append("## Flow ").append(flowNum++).append(": ")
              .append(method).append(" ").append(path).append("\n\n");

            appendMermaidFull(sb, method + " " + path, root);
            appendPlantUmlFull(sb, method + " " + path, root);
            sb.append("---\n\n");
        }

        if (!jobCallGraphs.isEmpty()) {
            sb.append("## Scheduled Jobs\n\n");
            for (Map.Entry<ScheduledJobInfo, CallNode> entry : jobCallGraphs.entrySet()) {
                ScheduledJobInfo job = entry.getKey();
                CallNode root = entry.getValue();
                String simpleClassName = job.getClassName().contains(".")
                        ? job.getClassName().substring(job.getClassName().lastIndexOf('.') + 1)
                        : job.getClassName();
                String title = simpleClassName + "::" + job.getMethodName();
                sb.append("### ").append(title).append("\n\n");
                appendMermaidFull(sb, title, root);
                appendPlantUmlFull(sb, title, root);
                sb.append("---\n\n");
            }
        }

        return sb.toString();
    }

    /** Builds a self-contained PlantUML activity diagram using all conditions (unfiltered). */
    public String buildPlantUmlSourceFull(String title, CallNode root) {
        StringBuilder sb = new StringBuilder();
        sb.append("@startuml\n");
        sb.append("!pragma layout smetana\n");
        sb.append("title ").append(title).append("\n");
        sb.append("start\n");
        renderPlantUmlNodeFull(sb, root, 0);
        sb.append("stop\n@enduml\n");
        return sb.toString();
    }

    /** Builds a self-contained Mermaid graph source string using all conditions (unfiltered). */
    public String buildMermaidSourceFull(String title, CallNode root) {
        StringBuilder sb = new StringBuilder();
        sb.append("graph TD\n");
        AtomicInteger counter = new AtomicInteger(0);
        String startId = "N" + counter.getAndIncrement();
        sb.append("    ").append(startId).append("([\"")
          .append(escMermaid(title)).append("\"])\n");
        renderMermaidNodeFull(sb, root, startId, counter);
        return sb.toString();
    }

    private void appendMermaidFull(StringBuilder sb, String title, CallNode root) {
        sb.append("### Mermaid\n\n```mermaid\ngraph TD\n");
        AtomicInteger counter = new AtomicInteger(0);
        String startId = "N" + counter.getAndIncrement();
        sb.append("    ").append(startId).append("([\"")
          .append(escMermaid(title)).append("\"])\n");
        renderMermaidNodeFull(sb, root, startId, counter);
        sb.append("```\n\n");
    }

    private String renderMermaidNodeFull(StringBuilder sb, CallNode node,
                                         String parentId, AtomicInteger counter) {
        String myId = "N" + counter.getAndIncrement();
        String label = buildNodeLabel(node);
        sb.append("    ").append(myId).append("[\"").append(escMermaid(label)).append("\"]\n");
        sb.append("    ").append(parentId).append(" --> ").append(myId).append("\n");

        String chainId = myId;

        chainId = renderMermaidConditions(sb, node.getAllConditions(), chainId, counter);

        for (CallNode callee : node.getCallees()) {
            chainId = renderMermaidNodeFull(sb, callee, chainId, counter);
        }

        return chainId;
    }

    /**
     * Renders a list of conditions as Mermaid decision diamonds, chained from {@code chainId}.
     * When a Yes-branch throws an exception and there is no else, appends a terminal node
     * (circle-X) and does NOT advance the chain — the flow after the diamond continues
     * implicitly from the No path.
     */
    private String renderMermaidConditions(StringBuilder sb, List<FlowCondition> conditions,
                                           String chainId, AtomicInteger counter) {
        for (FlowCondition cond : conditions) {
            String condId = "N" + counter.getAndIncrement();
            sb.append("    ").append(condId).append("{\"")
              .append(escMermaid(truncate(cond.getConditionText(), 55))).append("?\"}\n");
            sb.append("    ").append(chainId).append(" --> ").append(condId).append("\n");

            boolean thenThrows = cond.getThenSummary() != null
                    && cond.getThenSummary().startsWith("throws");

            if (cond.isHasElse() && cond.getElseSummary() != null) {
                String elseId = "N" + counter.getAndIncrement();
                sb.append("    ").append(elseId).append("[\"")
                  .append(escMermaid(cond.getElseSummary())).append("\"]\n");
                sb.append("    ").append(condId).append(" -- No --> ").append(elseId).append("\n");
            } else if (cond.isHasElse()) {
                sb.append("    ").append(condId).append(" -- No --> N").append(counter.get()).append("\n");
            }

            if (cond.getThenSummary() != null) {
                String thenId = "N" + counter.getAndIncrement();
                sb.append("    ").append(thenId).append("[\"")
                  .append(escMermaid(cond.getThenSummary())).append("\"]\n");
                sb.append("    ").append(condId).append(" -- Yes --> ").append(thenId).append("\n");

                if (thenThrows && !cond.isHasElse()) {
                    // Guard clause: terminate this branch; chain stays on condId (No path)
                    String killId = "N" + counter.getAndIncrement();
                    sb.append("    ").append(killId).append("((X))\n");
                    sb.append("    ").append(thenId).append(" --> ").append(killId).append("\n");
                    chainId = condId;
                } else {
                    chainId = thenId;
                }
            } else {
                sb.append("    ").append(condId).append(" -- Yes --> ...\n");
                chainId = condId;
            }
        }
        return chainId;
    }

    private void appendPlantUmlFull(StringBuilder sb, String title, CallNode root) {
        sb.append("### PlantUML\n\n```plantuml\n");
        sb.append(buildPlantUmlSourceFull(title, root));
        sb.append("```\n\n");
    }

    /**
     * Derives the flows output file path from the main output file path.
     * {@code /path/to/api-spec.md} → {@code /path/to/api-spec-flows.md}
     */
    public static Path flowsOutputPath(Path mainOutputFile) {
        String name = mainOutputFile.getFileName().toString();
        String base = name.endsWith(".md") ? name.substring(0, name.length() - 3) : name;
        return mainOutputFile.resolveSibling(base + "-flows.md");
    }

    /**
     * Derives the full-flows output file path from the main output file path.
     * {@code /path/to/api-spec.md} → {@code /path/to/api-spec-flows-full.md}
     */
    public static Path flowsFullOutputPath(Path mainOutputFile) {
        String name = mainOutputFile.getFileName().toString();
        String base = name.endsWith(".md") ? name.substring(0, name.length() - 3) : name;
        return mainOutputFile.resolveSibling(base + "-flows-full.md");
    }
}
