package com.devmanchego.contextextractor.render;

import com.devmanchego.contextextractor.angular.model.*;
import com.devmanchego.contextextractor.frontend.FrontendFramework;
import com.devmanchego.contextextractor.java.model.ScheduledJobInfo;
import com.devmanchego.contextextractor.callgraph.CallNode;
import com.devmanchego.contextextractor.java.model.*;
import com.devmanchego.contextextractor.matching.EndpointMatcher;
import com.devmanchego.contextextractor.matching.MatchedFlow;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Generates the full Markdown document from the intermediate model.
 *
 * Section structure:
 *   ## 1. INDEX
 *   ## 2. API FLOWS
 *   ## 3. DATA MODEL
 *   ## 4. PERSISTENCE MAPPING
 *   ## 5. SPA / STATIC ROUTES
 *   ## 6. BACKGROUND JOBS (@Scheduled)
 *   ## 7. WARNINGS & LOW-CONFIDENCE MATCHES
 */
public final class MarkdownRenderer {

    private static final Logger log = LoggerFactory.getLogger(MarkdownRenderer.class);

    private final AnchorUtil anchors = new AnchorUtil();

    // -----------------------------------------------------------------------
    // Public API
    // -----------------------------------------------------------------------

    /** Relativizes an absolute file path against the project root for display. */
    private String rel(String absolutePath, RenderInput input) {
        if (absolutePath == null || absolutePath.isBlank()) return "";
        if (input.rootPath() == null) return absolutePath;
        try {
            Path p = Path.of(absolutePath).toAbsolutePath().normalize();
            Path rel = input.rootPath().relativize(p);
            // Use forward slashes for cross-platform readability in Markdown
            return rel.toString().replace('\\', '/');
        } catch (IllegalArgumentException e) {
            return absolutePath;
        }
    }

    public String render(RenderInput input) {
        StringBuilder sb = new StringBuilder();

        sb.append("# Full-Stack API Specification\n\n");
        sb.append("*Generated by java-angular-fullstack-extractor*\n\n");
        sb.append("---\n\n");

        renderIndex(sb, input);
        renderApiFlows(sb, input);
        renderDataModel(sb, input);
        renderPersistenceMapping(sb, input);
        renderSpaRoutes(sb, input);
        renderScheduledJobs(sb, input);
        renderWarnings(sb, input);

        return sb.toString();
    }

    // -----------------------------------------------------------------------
    // Section 1: INDEX
    // -----------------------------------------------------------------------

    private void renderIndex(StringBuilder sb, RenderInput input) {
        sb.append("## 1. INDEX\n\n");

        sb.append("### UI Components\n\n");
        if (input.angularProject().getComponents().isEmpty()) {
            sb.append("*No ").append(input.angularProject().getFramework().displayName())
              .append(" components found.*\n\n");
        } else {
            input.angularProject().getComponents().forEach(c ->
                    sb.append("- `").append(c.getClassName()).append("` — ")
                      .append(rel(c.getFilePath(), input)).append("\n"));
            sb.append("\n");
        }

        sb.append("### Backend Controllers\n\n");
        Map<String, List<EndpointInfo>> byController = input.javaEndpoints().stream()
                .collect(Collectors.groupingBy(EndpointInfo::getControllerClass, LinkedHashMap::new, Collectors.toList()));
        if (byController.isEmpty()) {
            sb.append("*No backend controllers found.*\n\n");
        } else {
            byController.forEach((ctrl, eps) -> {
                String src = eps.get(0).getSourceFile();
                sb.append("- `").append(ctrl).append("`");
                if (src != null) sb.append(" — ").append(rel(src, input));
                sb.append("\n");
            });
            sb.append("\n");
        }

        sb.append("### API Flows\n\n");
        if (input.matchResult().flows().isEmpty()) {
            sb.append("*No matched flows.*\n\n");
        } else {
            int i = 1;
            for (MatchedFlow flow : input.matchResult().flows()) {
                String heading = "2." + i + " " + flowTitle(flow);
                String anchor = AnchorUtil.toSlug(heading);
                sb.append("- [").append(heading).append("](#").append(anchor).append(")\n");
                i++;
            }
            sb.append("\n");
        }

        sb.append("### Data Contracts (Front ↔ DTO)\n\n");
        if (input.matchResult().flows().isEmpty()) {
            sb.append("*No matched data contracts.*\n\n");
        } else {
            input.matchResult().flows().stream()
                    .map(f -> f.getJavaEndpoint().getResponseType())
                    .filter(Objects::nonNull)
                    .distinct()
                    .forEach(type -> sb.append("- `").append(type).append("`\n"));
            sb.append("\n");
        }

        sb.append("### Persistence Contracts (DTO ↔ Entity)\n\n");
        if (input.persistenceMappings().isEmpty()) {
            sb.append("*No persistence mappings found.*\n\n");
        } else {
            input.persistenceMappings().forEach(pm ->
                    sb.append("- `").append(pm.getDto().getSimpleName())
                      .append("` ↔ `").append(pm.getEntity().getSimpleName()).append("`\n"));
            sb.append("\n");
        }

        sb.append("### SPA / Static Routes\n\n");
        List<EndpointInfo> spaRoutes = input.javaEndpoints().stream()
                .filter(EndpointInfo::isStaticRoute).toList();
        if (spaRoutes.isEmpty()) {
            sb.append("*No SPA / static-route controllers found.*\n\n");
        } else {
            spaRoutes.forEach(ep -> sb.append("- `[STATIC_ROUTE]` `")
                    .append(ep.getHttpVerb()).append(" ").append(ep.getPathTemplate())
                    .append("` — `").append(ep.getControllerClass()).append("`\n"));
            sb.append("\n");
        }

        sb.append("### Background Jobs (@Scheduled)\n\n");
        if (input.scheduledJobs().isEmpty()) {
            sb.append("*No @Scheduled methods found.*\n\n");
        } else {
            int i = 1;
            for (ScheduledJobInfo job : input.scheduledJobs()) {
                String heading = "6." + i + " " + job.getClassName() + "#" + job.getMethodName();
                String anchor  = AnchorUtil.toSlug(heading);
                sb.append("- [").append(heading).append("](#").append(anchor).append(")")
                  .append(" — ").append(job.scheduleDescription()).append("\n");
                i++;
            }
            sb.append("\n");
        }

        sb.append("### Unresolved / Low Confidence\n\n");
        appendUnresolvedIndex(sb, input);
    }

    private void appendUnresolvedIndex(StringBuilder sb, RenderInput input) {
        List<EndpointMatcher.UnmatchedAngularCall> ua = input.matchResult().unmatchedAngularCalls();
        List<EndpointInfo> uj = input.matchResult().unmatchedJavaEndpoints();
        if (ua.isEmpty() && uj.isEmpty()) {
            sb.append("*None.*\n\n");
            return;
        }
        String fwName = input.angularProject().getFramework().displayName();
        ua.forEach(u -> sb.append("- ⚠ Unmatched ").append(fwName).append(" call: `")
                .append(u.call().getHttpVerb()).append(" ")
                .append(u.normalizedKey().pathTemplate()).append("`\n"));
        uj.forEach(ep -> sb.append("- ⚠ Unmatched Java endpoint: `")
                .append(ep.getHttpVerb()).append(" ")
                .append(ep.getPathTemplate()).append("` in `")
                .append(ep.getControllerClass()).append("`\n"));
        sb.append("\n");
    }

    // -----------------------------------------------------------------------
    // Section 2: API FLOWS
    // -----------------------------------------------------------------------

    private void renderApiFlows(StringBuilder sb, RenderInput input) {
        sb.append("## 2. API FLOWS\n\n");
        if (input.matchResult().flows().isEmpty()) {
            sb.append("*No matched flows found.*\n\n");
            return;
        }

        int i = 1;
        for (MatchedFlow flow : input.matchResult().flows()) {
            String title = "2." + i + " " + flowTitle(flow);
            sb.append("### ").append(title).append("\n\n");
            sb.append("```\n");
            renderFlowTree(sb, flow, input);
            sb.append("```\n\n");
            i++;
        }
    }

    private void renderFlowTree(StringBuilder sb, MatchedFlow flow, RenderInput input) {
        EndpointInfo ep = flow.getJavaEndpoint();
        HttpCallInfo call = flow.getAngularCall();
        ServiceInfo svc = flow.getAngularService();

        // ACTION line
        sb.append("# ACTION: ").append(call.getHttpVerb()).append(" ").append(ep.getPathTemplate()).append("\n");
        if (flow.isFuzzyMatch()) {
            sb.append("# ⚠ FUZZY MATCH — frontend URL '").append(call.getUrlTemplate())
              .append("' matched via literal-segment inference (verify manually)\n");
        }

        // FRONTEND block
        sb.append("# FRONTEND: ").append(rel(svc.getFilePath(), input)).append("\n");
        sb.append("  |--> [SERVICE] ").append(svc.getClassName())
          .append(" :: ").append(call.getMethodName());
        if (call.getResponseType() != null && !call.getResponseType().isBlank()
                && !"void".equals(call.getResponseType()) && !"any".equals(call.getResponseType())) {
            sb.append(" : Observable<").append(call.getResponseType()).append(">");
        }
        sb.append("\n");
        sb.append("       |--> [HTTP] ").append(call.getHttpVerb()).append(" ").append(call.getUrlTemplate()).append("\n");
        sb.append("            |-- (Network Bridge)\n");

        // BACKEND block
        sb.append("# BACKEND: ").append(rel(ep.getSourceFile(), input)).append("\n");
        String controllerEntry = "  |--> [CONTROLLER] " + shortName(ep.getControllerClass())
                + " :: " + ep.getMethodName();
        if (ep.getBodyParameterType() != null) {
            controllerEntry += "(" + ep.getBodyParameterType() + " body)";
        }
        if (ep.getResponseType() != null && !ep.getResponseType().isBlank()) {
            controllerEntry += " : " + ep.getResponseType();
        }
        sb.append(controllerEntry).append("\n");

        CallNode root = input.callGraphs().get(ep);
        if (root != null) {
            root.getCallees().forEach(child -> renderCallTreeNode(sb, child, 2));
        }
    }

    private void renderCallTreeNode(StringBuilder sb, CallNode node, int depth) {
        String indent = "  ".repeat(depth) + "     ";
        sb.append(indent).append("|--> [").append(node.getRole()).append("] ")
          .append(node.getClassName()).append(" :: ").append(node.getMethodName());
        if (node.isTransactional()) sb.append(" [@Tx]");
        sb.append("\n");
        node.getCallees().forEach(child -> renderCallTreeNode(sb, child, depth + 1));
    }

    // -----------------------------------------------------------------------
    // Section 3: DATA MODEL
    // -----------------------------------------------------------------------

    private void renderDataModel(StringBuilder sb, RenderInput input) {
        sb.append("## 3. DATA MODEL\n\n");
        sb.append("*Frontend (TypeScript) ↔ Backend (DTO) contracts.*\n\n");

        Map<String, TsModelInfo> tsModels = input.angularProject().getModels().stream()
                .collect(Collectors.toMap(TsModelInfo::getName, m -> m,
                        (a, b) -> a));

        int idx = 1;
        for (MatchedFlow flow : input.matchResult().flows()) {
            EndpointInfo ep = flow.getJavaEndpoint();

            // Response model
            if (ep.getResponseType() != null && flow.getTsResponseModel().isPresent()) {
                DtoInfo dto = lookupDto(ep.getResponseType(), input.dtosMap());
                sb.append("### 3.").append(idx).append(" ")
                  .append(ep.getResponseType()).append(" ↔ ")
                  .append(flow.getTsResponseModel().get().getName()).append("\n\n");
                renderDataModelTable(sb, flow.getTsResponseModel().get(), dto, input);
                idx++;
            }

            // Request model
            if (ep.getBodyParameterType() != null && flow.getTsRequestModel().isPresent()) {
                DtoInfo dto = lookupDto(ep.getBodyParameterType(), input.dtosMap());
                sb.append("### 3.").append(idx).append(" ")
                  .append(ep.getBodyParameterType()).append(" ↔ ")
                  .append(flow.getTsRequestModel().get().getName()).append("\n\n");
                renderDataModelTable(sb, flow.getTsRequestModel().get(), dto, input);
                idx++;
            }
        }

        if (idx == 1) {
            sb.append("*No correlated data contracts to display.*\n\n");
        }
    }

    private void renderDataModelTable(StringBuilder sb, TsModelInfo ts, DtoInfo dto,
                                      RenderInput input) {
        sb.append("| TS Field | TS Type | Java Field | Java Type | Rules |\n");
        sb.append("|---|---|---|---|---|\n");

        Map<String, FieldInfo> dtoFieldMap = dto == null ? Map.of()
                : dto.getFields().stream().collect(Collectors.toMap(FieldInfo::getName, f -> f, (a, b) -> a));

        for (TsFieldInfo tsField : ts.getFields()) {
            FieldInfo javaField = dtoFieldMap.get(tsField.getName());
            String javaFieldName = javaField != null ? javaField.getName() : "[no match]";
            String javaType = javaField != null ? javaField.getType() : "";
            String rules = javaField != null
                    ? String.join(", ", javaField.getValidationRules())
                    : "";
            sb.append("| `").append(tsField.getName()).append(tsField.isOptional() ? "?" : "")
              .append("` | `").append(tsField.getType()).append("` | `")
              .append(javaFieldName).append("` | `").append(javaType)
              .append("` | ").append(rules).append(" |\n");
        }
        sb.append("\n");
    }

    // -----------------------------------------------------------------------
    // Section 4: PERSISTENCE MAPPING
    // -----------------------------------------------------------------------

    private void renderPersistenceMapping(StringBuilder sb, RenderInput input) {
        sb.append("## 4. PERSISTENCE MAPPING\n\n");

        if (input.persistenceMappings().isEmpty()) {
            sb.append("*No persistence mappings found.*\n\n");
            return;
        }

        int idx = 1;
        for (PersistenceMapping pm : input.persistenceMappings()) {
            sb.append("### 4.").append(idx).append(" ")
              .append(pm.getDto().getSimpleName()).append(" ↔ ")
              .append(pm.getEntity().getSimpleName()).append("\n\n");

            if (pm.hasMapper()) {
                sb.append("**Mapper:** `").append(pm.getMapperClass()).append("`\n\n");
            }

            // Field mapping table
            sb.append("#### Field Mapping\n\n");
            sb.append("| DTO Field | DTO Type | Entity Field | Entity Type | Confidence |\n");
            sb.append("|---|---|---|---|---|\n");
            for (MappingRow row : pm.getRows()) {
                String confidence = switch (row.getConfidence()) {
                    case EXPLICIT  -> "explicit";
                    case IMPLICIT  -> "(implicit)";
                    case NO_MATCH  -> "[no match]";
                };
                if (row.isDtoOnly())    confidence += " [DTO-only]";
                if (row.isEntityOnly()) confidence += " [Entity-only]";
                sb.append("| `").append(row.getDtoField()).append("` | `").append(row.getDtoType())
                  .append("` | `").append(row.getEntityField()).append("` | `")
                  .append(row.getEntityType()).append("` | ").append(confidence).append(" |\n");
            }
            sb.append("\n");

            // Relations block
            EntityInfo entity = pm.getEntity();
            if (!entity.getRelations().isEmpty()) {
                sb.append("#### Relations\n\n");
                sb.append("| Field | Type | Kind | Join Column | Mapped By |\n");
                sb.append("|---|---|---|---|---|\n");
                entity.getRelations().forEach(r ->
                        sb.append("| `").append(r.getFieldName()).append("` | `")
                          .append(r.getTargetEntityType()).append("` | ")
                          .append(r.getKind()).append(" | ")
                          .append(r.getJoinColumn() != null ? "`" + r.getJoinColumn() + "`" : "—").append(" | ")
                          .append(r.getMappedBy() != null ? "`" + r.getMappedBy() + "`" : "—").append(" |\n"));
                sb.append("\n");
            }

            // Repository block
            if (!entity.getRepositoryMethods().isEmpty()) {
                sb.append("#### Repository\n\n");
                sb.append("| Method | Return Type | Query |\n");
                sb.append("|---|---|---|\n");
                entity.getRepositoryMethods().forEach(rm ->
                        sb.append("| `").append(rm.getMethodName()).append("` | `")
                          .append(rm.getReturnType()).append("` | ")
                          .append(rm.hasQuery() ? "`" + rm.getQueryLiteral().replace("|", "\\|") + "`" : "—")
                          .append(" |\n"));
                sb.append("\n");
            }

            idx++;
        }
    }

    // -----------------------------------------------------------------------
    // Section 5: SPA / STATIC ROUTES
    // -----------------------------------------------------------------------

    private void renderSpaRoutes(StringBuilder sb, RenderInput input) {
        sb.append("## 5. SPA / STATIC ROUTES\n\n");
        List<EndpointInfo> spaRoutes = input.javaEndpoints().stream()
                .filter(EndpointInfo::isStaticRoute).toList();
        if (spaRoutes.isEmpty()) {
            sb.append("*No SPA / static-route controllers detected.*\n\n");
            return;
        }
        sb.append("*These endpoints are served by `@Controller` (view-returning) classes — "
                + "typically SPA index.html forwards. They are intentionally excluded from "
                + "API flow matching and unmatched-endpoint warnings.*\n\n");
        sb.append("| Path | Controller | Method | Source |\n");
        sb.append("|---|---|---|---|\n");
        spaRoutes.forEach(ep ->
                sb.append("| `").append(ep.getPathTemplate()).append("` | `")
                  .append(shortName(ep.getControllerClass())).append("` | `")
                  .append(ep.getMethodName()).append("` | ")
                  .append(rel(ep.getSourceFile(), input)).append(" |\n"));
        sb.append("\n");
    }

    // -----------------------------------------------------------------------
    // Section 6: BACKGROUND JOBS
    // -----------------------------------------------------------------------

    private void renderScheduledJobs(StringBuilder sb, RenderInput input) {
        sb.append("## 6. BACKGROUND JOBS (@Scheduled)\n\n");
        if (input.scheduledJobs().isEmpty()) {
            sb.append("*No @Scheduled methods found.*\n\n");
            return;
        }

        int i = 1;
        for (ScheduledJobInfo job : input.scheduledJobs()) {
            String title = "6." + i + " " + job.getClassName() + "#" + job.getMethodName();
            sb.append("### ").append(title).append("\n\n");
            sb.append("```\n");
            sb.append("# JOB: ").append(job.getClassName()).append(" :: ").append(job.getMethodName()).append("\n");
            sb.append("# SCHEDULE: ").append(job.scheduleDescription()).append("\n");
            if (job.getInitialDelay() != null) {
                sb.append("# INITIAL_DELAY: ").append(job.getInitialDelay()).append("\n");
            }
            sb.append("# BACKEND: ").append(rel(job.getSourceFile(), input)).append("\n");

            CallNode root = input.jobCallGraphs().get(job);
            if (root != null) {
                root.getCallees().forEach(child -> renderCallTreeNode(sb, child, 1));
            }
            sb.append("```\n\n");
            i++;
        }
    }

    // -----------------------------------------------------------------------
    // Section 7: WARNINGS
    // -----------------------------------------------------------------------

    /**
     * Describes why the JVM parser (Strategy B) ran, when it did — Node.js being absent is
     * only one of two legitimate reasons. A framework with no TypeScript project for ts-morph
     * to load (JSP + jQuery) skips Strategy A deliberately, regardless of whether Node.js
     * happens to be on {@code PATH}; labelling that case "Node.js not available" would be
     * simply wrong on a machine where it is.
     */
    private String strategyLabel(AngularProject project) {
        if (project.getStrategy() == AngularProject.ParsingStrategy.NODE_TS_MORPH) {
            return "Strategy A — Node.js + ts-morph";
        }
        if (project.getFramework() == FrontendFramework.JSP_JQUERY) {
            return "Strategy B — JVM parser (Strategy A does not apply to this framework)";
        }
        return "Strategy B — JVM ANTLR parser (Node.js not available)";
    }

    private void renderWarnings(StringBuilder sb, RenderInput input) {
        sb.append("## 7. WARNINGS & LOW-CONFIDENCE MATCHES\n\n");

        String framework = input.angularProject().getFramework().displayName();
        sb.append("**Frontend framework:** ").append(framework).append("  \n");
        sb.append("**TypeScript parsing strategy:** ")
          .append(strategyLabel(input.angularProject()))
          .append("\n\n");

        boolean hasWarnings = false;

        if (input.angularProject().isUninterpreted()) {
            sb.append("- **⚠️ Frontend not analysed:** found ")
              .append(input.angularProject().getScannedSourceFileCount())
              .append(" frontend source file(s) under the project root, but extracted no ")
              .append("components, services, routes, or data models from them. Every section in ")
              .append("this document derived from the frontend — API Flows, Data Contracts, ")
              .append("Application Sections, Frontend Pages, Site Map — reflects an ")
              .append("**uninterpreted** frontend, not a confirmed-empty one. In particular, the ")
              .append("unmatched-Java-endpoint warnings below do **not** mean the frontend makes ")
              .append("no HTTP calls to them.\n");
            hasWarnings = true;
        }

        List<MatchedFlow> fuzzyFlows = input.matchResult().flows().stream()
                .filter(MatchedFlow::isFuzzyMatch).toList();
        if (!fuzzyFlows.isEmpty()) {
            sb.append("- **Fuzzy matches (").append(fuzzyFlows.size())
              .append("):** the following flows were matched by inferring that a literal "
                    + "frontend path segment corresponds to a backend `{param}` variable. "
                    + "Verify each one manually or re-run with `--strict-matching` to exclude them:\n");
            for (MatchedFlow f : fuzzyFlows) {
                sb.append("  - `").append(f.getAngularCall().getHttpVerb())
                  .append(" ").append(f.getAngularCall().getUrlTemplate())
                  .append("` → `").append(f.getJavaEndpoint().getHttpVerb())
                  .append(" ").append(f.getJavaEndpoint().getPathTemplate()).append("`\n");
            }
            hasWarnings = true;
        }

        for (EndpointMatcher.UnmatchedAngularCall u : input.matchResult().unmatchedAngularCalls()) {
            sb.append("- **Unmatched ").append(framework).append(" call:** `")
              .append(u.call().getHttpVerb()).append(" ").append(u.normalizedKey().pathTemplate())
              .append("` in `").append(u.service().getClassName()).append("#")
              .append(u.call().getMethodName()).append("`")
              .append(" — no Java endpoint found for this path.\n");
            hasWarnings = true;
        }

        for (EndpointInfo ep : input.matchResult().unmatchedJavaEndpoints()) {
            sb.append("- **Unmatched Java endpoint:** `")
              .append(ep.getHttpVerb()).append(" ").append(ep.getPathTemplate())
              .append("` in `").append(ep.getControllerClass())
              .append("` — no ").append(framework).append(" call targets this endpoint.\n");
            hasWarnings = true;
        }

        for (String warn : input.unresolvedUrlWarnings()) {
            sb.append("- **Unresolved dynamic URL:** ").append(warn).append("\n");
            hasWarnings = true;
        }

        for (String warn : input.callGraphCycleWarnings()) {
            sb.append("- **Call graph cycle:** ").append(warn).append("\n");
            hasWarnings = true;
        }

        if (input.classpathDegraded()) {
            sb.append("- **Degraded type resolution:** classpath could not be resolved via Maven. "
                    + "Generic type parameters may be incorrect or missing.\n");
            hasWarnings = true;
        }

        for (String nameCollision : input.nameCollisions()) {
            sb.append("- **Name collision:** ").append(nameCollision).append("\n");
            hasWarnings = true;
        }

        if (!hasWarnings) {
            sb.append("*No warnings.*\n");
        }
        sb.append("\n");
    }

    // -----------------------------------------------------------------------
    // Shared helpers
    // -----------------------------------------------------------------------

    // -----------------------------------------------------------------------
    // DTO lookup helpers
    // -----------------------------------------------------------------------

    private static final List<String> NORMALIZE_SUFFIXES = List.of(
            "DTO", "Dto", "Response", "Request", "Command", "Query",
            "Payload", "Result", "Data", "Info", "Params", "Body", "Form");

    /**
     * Looks up a {@link DtoInfo} by Java type name.
     * First tries an exact match; if not found, strips array suffix ({@code []}) and
     * retries; finally falls back to a normalized name comparison (stripping common
     * DTO suffixes) to handle cases like {@code HealthScore} matching {@code HealthScoreDto}.
     */
    private DtoInfo lookupDto(String typeName, Map<String, DtoInfo> dtosMap) {
        if (typeName == null || dtosMap.isEmpty()) return null;
        // Exact match
        DtoInfo found = dtosMap.get(typeName);
        if (found != null) return found;
        // Strip array suffix
        String base = typeName.endsWith("[]") ? typeName.substring(0, typeName.length() - 2) : typeName;
        found = dtosMap.get(base);
        if (found != null) return found;
        // Normalized fallback
        String normalizedTarget = normalizeDtoName(base);
        return dtosMap.values().stream()
                .filter(d -> normalizeDtoName(d.getSimpleName()).equalsIgnoreCase(normalizedTarget))
                .findFirst()
                .orElse(null);
    }

    private String normalizeDtoName(String name) {
        if (name == null) return "";
        for (String suffix : NORMALIZE_SUFFIXES) {
            if (name.endsWith(suffix) && name.length() > suffix.length()) {
                return name.substring(0, name.length() - suffix.length()).toLowerCase();
            }
        }
        return name.toLowerCase();
    }

    private String flowTitle(MatchedFlow flow) {
        return flow.getAngularCall().getHttpVerb() + " "
                + flow.getJavaEndpoint().getPathTemplate();
    }

    private String shortName(String fqn) {
        if (!fqn.contains(".")) return fqn;
        return fqn.substring(fqn.lastIndexOf('.') + 1);
    }

    // -----------------------------------------------------------------------
    // Input DTO
    // -----------------------------------------------------------------------

    /**
     * All data the renderer needs, assembled by the Application orchestrator.
     * {@code rootPath} is the common ancestor of both project paths; all file paths
     * in the output are relativized against it.
     */
    public record RenderInput(
            AngularProject angularProject,
            List<EndpointInfo> javaEndpoints,
            EndpointMatcher.MatchResult matchResult,
            List<PersistenceMapping> persistenceMappings,
            Map<String, DtoInfo> dtosMap,                      // simple type name → DtoInfo
            Map<EndpointInfo, CallNode> callGraphs,
            List<ScheduledJobInfo> scheduledJobs,
            Map<ScheduledJobInfo, CallNode> jobCallGraphs,
            List<String> callGraphCycleWarnings,
            List<String> unresolvedUrlWarnings,
            boolean classpathDegraded,
            List<String> nameCollisions,
            Path rootPath) {}
}
