package com.devmanchego.contextextractor.render;

import com.devmanchego.contextextractor.callgraph.CallNode;
import com.devmanchego.contextextractor.callgraph.FlowCondition;
import com.devmanchego.contextextractor.java.model.EndpointInfo;
import com.devmanchego.contextextractor.java.model.ScheduledJobInfo;
import com.devmanchego.contextextractor.matching.MatchedFlow;

import java.nio.file.Path;
import java.util.*;

/**
 * Generates a Markdown file with Mermaid {@code sequenceDiagram} and PlantUML sequence diagrams
 * for each matched API flow and each scheduled job.
 *
 * Output file naming: if main output is {@code api-spec.md}, this writes {@code api-spec-sequence.md}.
 */
public final class SequenceDiagramRenderer {

    private static final int MAX_LABEL_LEN = 40;

    public String render(List<MatchedFlow> flows,
                         Map<EndpointInfo, CallNode> callGraphs,
                         Map<ScheduledJobInfo, CallNode> jobCallGraphs,
                         Path rootPath) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Full-Stack API Sequence Diagrams\n\n");
        sb.append("*Generated by java-angular-fullstack-extractor*\n\n");
        sb.append("---\n\n");

        int flowNum = 1;
        for (MatchedFlow flow : flows) {
            CallNode root = callGraphs.get(flow.getJavaEndpoint());
            if (root == null) continue;

            String method = flow.getAngularCall().getHttpVerb().name();
            String path   = flow.getJavaEndpoint().getPathTemplate();
            String title  = method + " " + path;

            sb.append("## Flow ").append(flowNum++).append(": ").append(title).append("\n\n");

            appendMermaidSequence(sb, title, flow, root);
            appendPlantUmlSequence(sb, title, flow, root);
            sb.append("---\n\n");
        }

        if (!jobCallGraphs.isEmpty()) {
            sb.append("## Scheduled Jobs\n\n");
            for (Map.Entry<ScheduledJobInfo, CallNode> entry : jobCallGraphs.entrySet()) {
                ScheduledJobInfo job  = entry.getKey();
                CallNode         root = entry.getValue();
                String simpleClassName = job.getClassName().contains(".")
                        ? job.getClassName().substring(job.getClassName().lastIndexOf('.') + 1)
                        : job.getClassName();
                String title = simpleClassName + "::" + job.getMethodName();
                sb.append("### ").append(title).append("\n\n");
                appendMermaidSequenceForJob(sb, title, job, root);
                appendPlantUmlSequenceForJob(sb, title, job, root);
                sb.append("---\n\n");
            }
        }

        return sb.toString();
    }

    // -----------------------------------------------------------------------
    // Static path helper
    // -----------------------------------------------------------------------

    /**
     * Derives the sequence output file path from the main output file path.
     * {@code /path/to/api-spec.md} → {@code /path/to/api-spec-sequence.md}
     */
    public static Path sequenceOutputPath(Path mainOutputFile) {
        String name = mainOutputFile.getFileName().toString();
        String base = name.endsWith(".md") ? name.substring(0, name.length() - 3) : name;
        return mainOutputFile.resolveSibling(base + "-sequence.md");
    }

    // -----------------------------------------------------------------------
    // Public PlantUML builder (for use by PNG exporter)
    // -----------------------------------------------------------------------

    public String buildPlantUmlSequenceSource(String title, MatchedFlow flow, CallNode root) {
        StringBuilder sb = new StringBuilder();
        sb.append("@startuml\n");
        sb.append("!pragma layout smetana\n");
        sb.append("title ").append(title).append("\n");

        // Collect participants
        String angularAlias    = "Angular";
        String controllerAlias = "Controller";
        String angularName  = flow.getAngularService().getClassName();
        String controllerName = simpleClassName(flow.getJavaEndpoint().getControllerClass());

        List<String[]> participants = new ArrayList<>(); // [alias, fullName]
        participants.add(new String[]{"Browser", "Browser"});
        participants.add(new String[]{angularAlias, angularName});
        participants.add(new String[]{controllerAlias, controllerName});

        List<String[]> treeParticipants = new ArrayList<>();
        collectParticipants(root, treeParticipants, new LinkedHashSet<>());
        // Skip controller (already added)
        for (String[] p : treeParticipants) {
            if (!p[0].equals(controllerName)) {
                participants.add(new String[]{p[0] + "Participant", p[0]});
            }
        }

        // De-duplicate by alias
        List<String[]> dedupedParticipants = deduplicateParticipants(participants);

        // actor / participant declarations
        sb.append("actor Browser\n");
        for (int i = 1; i < dedupedParticipants.size(); i++) {
            String[] p = dedupedParticipants.get(i);
            sb.append("participant \"").append(escPuml(truncate(p[1], MAX_LABEL_LEN)))
              .append("\" as ").append(p[0]).append("\n");
        }

        // Interactions: Browser -> Angular
        String httpVerb = flow.getAngularCall().getHttpVerb().name();
        String httpPath = flow.getJavaEndpoint().getPathTemplate();
        String angularMethod = flow.getAngularCall().getMethodName();
        String angularReturn = flow.getAngularCall().getResponseType();

        sb.append("Browser -> ").append(angularAlias).append(" : ")
          .append(escPuml(truncate(angularMethod + "()", MAX_LABEL_LEN))).append("\n");
        sb.append(angularAlias).append(" -> ").append(controllerAlias).append(" : ")
          .append(escPuml(truncate(httpVerb + " " + httpPath, MAX_LABEL_LEN))).append("\n");

        // Render call graph nodes starting from root (controller)
        renderPlantUmlNode(sb, root, buildAliasMap(dedupedParticipants, controllerAlias));

        // Return path
        sb.append(controllerAlias).append(" --> ").append(angularAlias).append(" : 200 OK\n");
        sb.append(angularAlias).append(" --> Browser : ")
          .append(escPuml(truncate("Observable<" + (angularReturn != null ? angularReturn : "void") + ">",
                  MAX_LABEL_LEN)))
          .append("\n");

        sb.append("@enduml\n");
        return sb.toString();
    }

    public String buildPlantUmlSequenceSourceForJob(String title, ScheduledJobInfo job, CallNode root) {
        StringBuilder sb = new StringBuilder();
        sb.append("@startuml\n");
        sb.append("!pragma layout smetana\n");
        sb.append("title ").append(title).append("\n");

        List<String[]> treeParticipants = new ArrayList<>();
        collectParticipants(root, treeParticipants, new LinkedHashSet<>());
        List<String[]> dedupedParticipants = deduplicateParticipants(treeParticipants);

        for (String[] p : dedupedParticipants) {
            sb.append("participant \"").append(escPuml(truncate(p[1], MAX_LABEL_LEN)))
              .append("\" as ").append(p[0]).append("\n");
        }

        Map<String, String> aliasMap = buildAliasMap(dedupedParticipants, null);
        if (!dedupedParticipants.isEmpty()) {
            renderPlantUmlNode(sb, root, aliasMap);
        }

        sb.append("@enduml\n");
        return sb.toString();
    }

    // -----------------------------------------------------------------------
    // Mermaid sequence
    // -----------------------------------------------------------------------

    private void appendMermaidSequence(StringBuilder sb, String title, MatchedFlow flow, CallNode root) {
        sb.append("### Mermaid\n\n```mermaid\nsequenceDiagram\n");

        String angularAlias    = "AngularService";
        String controllerAlias = "Controller";
        String angularName     = flow.getAngularService().getClassName();
        String controllerName  = simpleClassName(flow.getJavaEndpoint().getControllerClass());

        // Participants
        sb.append("    participant Browser\n");
        sb.append("    participant ").append(angularAlias)
          .append(" as ").append(escMermaid(truncate(angularName, MAX_LABEL_LEN))).append("\n");
        sb.append("    participant ").append(controllerAlias)
          .append(" as ").append(escMermaid(truncate(controllerName, MAX_LABEL_LEN))).append("\n");

        List<String[]> treeParticipants = new ArrayList<>();
        collectParticipants(root, treeParticipants, new LinkedHashSet<>());
        List<String[]> extraAliases = new ArrayList<>();
        for (String[] p : treeParticipants) {
            if (!p[0].equals(controllerName)) {
                String alias = p[0] + "Seq";
                sb.append("    participant ").append(alias)
                  .append(" as ").append(escMermaid(truncate(p[0], MAX_LABEL_LEN))).append("\n");
                extraAliases.add(new String[]{p[0], alias});
            }
        }

        // Build alias map: className -> alias for mermaid
        Map<String, String> aliasMap = new LinkedHashMap<>();
        aliasMap.put(angularName, angularAlias);
        aliasMap.put(controllerName, controllerAlias);
        for (String[] e : extraAliases) {
            aliasMap.put(e[0], e[1]);
        }
        // Also add by simple name for root node
        aliasMap.put(root.getClassName(), controllerAlias);

        // Interactions
        String httpVerb    = flow.getAngularCall().getHttpVerb().name();
        String httpPath    = flow.getJavaEndpoint().getPathTemplate();
        String angularMethod = flow.getAngularCall().getMethodName();
        String angularReturn = flow.getAngularCall().getResponseType();

        sb.append("    Browser->>").append(angularAlias).append(": ")
          .append(escMermaid(truncate(angularMethod + "()", MAX_LABEL_LEN))).append("\n");
        sb.append("    ").append(angularAlias).append("->>").append(controllerAlias).append(": ")
          .append(escMermaid(truncate(httpVerb + " " + httpPath, MAX_LABEL_LEN))).append("\n");

        // Render nodes
        renderMermaidNode(sb, root, controllerAlias, aliasMap, "    ");

        // Return path
        sb.append("    ").append(controllerAlias).append("-->>").append(angularAlias)
          .append(": 200 OK\n");
        sb.append("    ").append(angularAlias).append("-->>Browser: Observable<")
          .append(escMermaid(truncate(angularReturn != null ? angularReturn : "void", MAX_LABEL_LEN)))
          .append(">\n");

        sb.append("```\n\n");
    }

    private void appendMermaidSequenceForJob(StringBuilder sb, String title, ScheduledJobInfo job, CallNode root) {
        sb.append("### Mermaid\n\n```mermaid\nsequenceDiagram\n");

        List<String[]> treeParticipants = new ArrayList<>();
        collectParticipants(root, treeParticipants, new LinkedHashSet<>());
        List<String[]> dedupedParticipants = deduplicateParticipants(treeParticipants);

        for (String[] p : dedupedParticipants) {
            sb.append("    participant ").append(p[0])
              .append(" as ").append(escMermaid(truncate(p[1], MAX_LABEL_LEN))).append("\n");
        }

        Map<String, String> aliasMap = new LinkedHashMap<>();
        for (String[] p : dedupedParticipants) {
            aliasMap.put(p[1], p[0]);
        }
        if (!dedupedParticipants.isEmpty()) {
            renderMermaidNode(sb, root, aliasMap.getOrDefault(root.getClassName(), root.getClassName()),
                    aliasMap, "    ");
        }

        sb.append("```\n\n");
    }

    private void renderMermaidNode(StringBuilder sb, CallNode node, String myAlias,
                                   Map<String, String> aliasMap, String indent) {
        // @Transactional note
        if (node.isTransactional()) {
            sb.append(indent).append("note over ").append(myAlias).append(": @Transactional\n");
        }

        // Conditions before callees
        for (FlowCondition cond : node.getConditions()) {
            sb.append(indent).append("alt ").append(escMermaid(truncate(cond.getConditionText(), MAX_LABEL_LEN))).append("\n");
            if (cond.getThenSummary() != null) {
                sb.append(indent).append("    note over ").append(myAlias).append(": ")
                  .append(escMermaid(truncate(cond.getThenSummary(), MAX_LABEL_LEN))).append("\n");
            }
            if (cond.isHasElse()) {
                sb.append(indent).append("else No\n");
                if (cond.getElseSummary() != null) {
                    sb.append(indent).append("    note over ").append(myAlias).append(": ")
                      .append(escMermaid(truncate(cond.getElseSummary(), MAX_LABEL_LEN))).append("\n");
                }
            }
            sb.append(indent).append("end\n");
        }

        // Callees
        for (CallNode callee : node.getCallees()) {
            String calleeAlias = aliasMap.getOrDefault(callee.getClassName(),
                    callee.getClassName() + "Seq");
            String returnType = callee.getReturnType() != null ? callee.getReturnType() : "void";

            // Forward call
            sb.append(indent).append(myAlias).append("->>").append(calleeAlias).append(": ")
              .append(escMermaid(truncate(callee.getMethodName() + "()", MAX_LABEL_LEN))).append("\n");

            // Recurse into callee
            renderMermaidNode(sb, callee, calleeAlias, aliasMap, indent);

            // Return
            sb.append(indent).append(calleeAlias).append("-->>").append(myAlias).append(": ")
              .append(escMermaid(truncate(returnType, MAX_LABEL_LEN))).append("\n");
        }
    }

    // -----------------------------------------------------------------------
    // PlantUML sequence
    // -----------------------------------------------------------------------

    private void appendPlantUmlSequence(StringBuilder sb, String title, MatchedFlow flow, CallNode root) {
        sb.append("### PlantUML\n\n```plantuml\n");
        sb.append(buildPlantUmlSequenceSource(title, flow, root));
        sb.append("```\n\n");
    }

    private void appendPlantUmlSequenceForJob(StringBuilder sb, String title,
                                               ScheduledJobInfo job, CallNode root) {
        sb.append("### PlantUML\n\n```plantuml\n");
        sb.append(buildPlantUmlSequenceSourceForJob(title, job, root));
        sb.append("```\n\n");
    }

    private void renderPlantUmlNode(StringBuilder sb, CallNode node, Map<String, String> aliasMap) {
        String myAlias = aliasMap.getOrDefault(node.getClassName(), node.getClassName());

        if (node.isTransactional()) {
            sb.append("note over ").append(myAlias).append(": @Transactional\n");
        }

        for (FlowCondition cond : node.getConditions()) {
            sb.append("alt ").append(escPuml(truncate(cond.getConditionText(), MAX_LABEL_LEN))).append("\n");
            if (cond.getThenSummary() != null) {
                sb.append("    note over ").append(myAlias).append(": ")
                  .append(escPuml(truncate(cond.getThenSummary(), MAX_LABEL_LEN))).append("\n");
            }
            if (cond.isHasElse()) {
                sb.append("else\n");
                if (cond.getElseSummary() != null) {
                    sb.append("    note over ").append(myAlias).append(": ")
                      .append(escPuml(truncate(cond.getElseSummary(), MAX_LABEL_LEN))).append("\n");
                }
            }
            sb.append("end\n");
        }

        for (CallNode callee : node.getCallees()) {
            String calleeAlias = aliasMap.getOrDefault(callee.getClassName(),
                    callee.getClassName() + "Participant");
            String returnType = callee.getReturnType() != null ? callee.getReturnType() : "void";

            sb.append(myAlias).append(" -> ").append(calleeAlias).append(" : ")
              .append(escPuml(truncate(callee.getMethodName() + "()", MAX_LABEL_LEN))).append("\n");

            renderPlantUmlNode(sb, callee, aliasMap);

            sb.append(calleeAlias).append(" --> ").append(myAlias).append(" : ")
              .append(escPuml(truncate(returnType, MAX_LABEL_LEN))).append("\n");
        }
    }

    // -----------------------------------------------------------------------
    // Participant collection (pre-order traversal, unique class names)
    // -----------------------------------------------------------------------

    private void collectParticipants(CallNode node, List<String[]> result, Set<String> seen) {
        String name = node.getClassName();
        if (seen.add(name)) {
            result.add(new String[]{name, name});
        }
        for (CallNode callee : node.getCallees()) {
            collectParticipants(callee, result, seen);
        }
    }

    /**
     * Build an alias map from a deduplicated list of [alias, name] pairs.
     * controllerAlias overrides the first entry's alias when provided.
     */
    private Map<String, String> buildAliasMap(List<String[]> participants, String controllerAlias) {
        Map<String, String> map = new LinkedHashMap<>();
        for (String[] p : participants) {
            map.put(p[1], p[0]); // name -> alias
        }
        return map;
    }

    /**
     * De-duplicates participants by name (first occurrence wins), assigning unique aliases.
     * Returns list of [alias, name].
     */
    private List<String[]> deduplicateParticipants(List<String[]> input) {
        List<String[]> result = new ArrayList<>();
        Set<String> seenNames = new LinkedHashSet<>();
        for (String[] p : input) {
            if (seenNames.add(p[1])) {
                result.add(p);
            }
        }
        return result;
    }

    // -----------------------------------------------------------------------
    // Escape helpers
    // -----------------------------------------------------------------------

    private String escMermaid(String s) {
        // Mermaid sequenceDiagram rejects HTML entities in message labels.
        // Replace generic brackets with square brackets so List<Foo> → List[Foo].
        return s.replace("\"", "'");
    }

    private String escPuml(String s) {
        if (s == null || s.isEmpty()) return "\"\"";
        // Also neutralize angle brackets: with no global sanitization at export time,
        // raw < > in labels would be parsed as creole markup by PlantUML.
        String escaped = s.replace("\"", "\\\"").replace("<", "~").replace(">", "~");
        return "\"" + escaped + "\"";
    }

    private String truncate(String s, int max) {
        if (s == null) return "";
        return s.length() <= max ? s : s.substring(0, max - 3) + "...";
    }

    private String simpleClassName(String fqn) {
        if (fqn == null) return "Unknown";
        return fqn.contains(".") ? fqn.substring(fqn.lastIndexOf('.') + 1) : fqn;
    }
}
