package com.devmanchego.contextextractor.render;

import com.devmanchego.contextextractor.angular.model.HttpCallInfo;
import com.devmanchego.contextextractor.angular.model.ServiceInfo;
import com.devmanchego.contextextractor.callgraph.CallNode;
import com.devmanchego.contextextractor.java.model.EndpointInfo;
import com.devmanchego.contextextractor.java.model.HttpVerb;
import com.devmanchego.contextextractor.matching.MatchedFlow;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class ClassDiagramRendererTest {

    private final ClassDiagramRenderer renderer = new ClassDiagramRenderer();

    // -----------------------------------------------------------------------
    // classesOutputPath
    // -----------------------------------------------------------------------

    @Test
    void classesOutputPath_derivesCorrectName() {
        Path main   = Path.of("/output/api-spec.md");
        Path result = ClassDiagramRenderer.classesOutputPath(main);
        assertEquals("api-spec-classes.md", result.getFileName().toString());
    }

    // -----------------------------------------------------------------------
    // render() with empty flows
    // -----------------------------------------------------------------------

    @Test
    void render_emptyFlows_returnsValidMarkdownHeader() {
        String result = renderer.render(List.of(), Map.of(), Path.of("/tmp"));

        assertTrue(result.contains("# Full-Stack API Class Diagrams"));
        assertTrue(result.contains("*Generated by java-angular-fullstack-extractor*"));
    }

    // -----------------------------------------------------------------------
    // render() with a flow + CallNode contains classDiagram
    // -----------------------------------------------------------------------

    @Test
    void render_flowWithCallNode_containsClassDiagramKeyword() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.POST)
                .pathTemplate("/api/v1/accounts")
                .controllerClass("AccountController")
                .methodName("create")
                .framework("Spring")
                .build();

        CallNode root = new CallNode(
                "AccountController", "create",
                CallNode.Role.CONTROLLER,
                false, "AccountResponse",
                List.of(), null,
                List.of(),
                List.of()
        );

        HttpCallInfo httpCall = new HttpCallInfo("create", HttpVerb.POST, "/api/v1/accounts", "AccountResponse", "AccountRequest");
        ServiceInfo angularService = new ServiceInfo("AccountService", "account.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String result = renderer.render(List.of(flow), Map.of(endpoint, root), Path.of("/tmp"));

        assertTrue(result.contains("classDiagram"), "Should contain classDiagram keyword");
        assertTrue(result.contains("AccountController"), "Should contain controller class name");
    }

    // -----------------------------------------------------------------------
    // render() with implementedInterfaces contains ..|>
    // -----------------------------------------------------------------------

    @Test
    void render_nodeWithImplementedInterface_containsImplementsRelation() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.GET)
                .pathTemplate("/api/accounts")
                .controllerClass("AccountController")
                .methodName("list")
                .framework("Spring")
                .build();

        CallNode serviceNode = new CallNode(
                "AccountServiceImpl", "list",
                CallNode.Role.SERVICE,
                false, "List",
                List.of("IAccountService"), null,
                List.of(),
                List.of()
        );

        CallNode root = new CallNode(
                "AccountController", "list",
                CallNode.Role.CONTROLLER,
                false, "List",
                List.of(), null,
                List.of(),
                List.of(serviceNode)
        );

        HttpCallInfo httpCall = new HttpCallInfo("list", HttpVerb.GET, "/api/accounts", "AccountResponse[]", null);
        ServiceInfo angularService = new ServiceInfo("AccountService", "account.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String result = renderer.render(List.of(flow), Map.of(endpoint, root), Path.of("/tmp"));

        assertTrue(result.contains("..|>"), "Should contain implements relation ..|>");
        assertTrue(result.contains("IAccountService"), "Should reference the interface name");
    }

    // -----------------------------------------------------------------------
    // render() with superClass contains --|>
    // -----------------------------------------------------------------------

    @Test
    void render_nodeWithSuperClass_containsExtendsRelation() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.GET)
                .pathTemplate("/api/items")
                .controllerClass("ItemController")
                .methodName("get")
                .framework("Spring")
                .build();

        CallNode root = new CallNode(
                "ItemController", "get",
                CallNode.Role.CONTROLLER,
                false, "ItemResponse",
                List.of(), "BaseController",
                List.of(),
                List.of()
        );

        HttpCallInfo httpCall = new HttpCallInfo("get", HttpVerb.GET, "/api/items", "ItemResponse", null);
        ServiceInfo angularService = new ServiceInfo("ItemService", "item.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String result = renderer.render(List.of(flow), Map.of(endpoint, root), Path.of("/tmp"));

        assertTrue(result.contains("--|>"), "Should contain extends relation --|>");
        assertTrue(result.contains("BaseController"), "Should reference the superclass name");
    }

    // -----------------------------------------------------------------------
    // buildPlantUmlClassSource contains @startuml and @enduml
    // -----------------------------------------------------------------------

    @Test
    void buildPlantUmlClassSource_containsStartAndEndMarkers() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.POST)
                .pathTemplate("/api/v1/accounts")
                .controllerClass("AccountController")
                .methodName("create")
                .framework("Spring")
                .build();

        CallNode root = new CallNode(
                "AccountController", "create",
                CallNode.Role.CONTROLLER,
                false, "AccountResponse",
                List.of(), null,
                List.of(),
                List.of()
        );

        HttpCallInfo httpCall = new HttpCallInfo("create", HttpVerb.POST, "/api/v1/accounts", "AccountResponse", "AccountRequest");
        ServiceInfo angularService = new ServiceInfo("AccountService", "account.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String puml = renderer.buildPlantUmlClassSource("POST /api/v1/accounts", flow, root);

        assertTrue(puml.startsWith("@startuml"), "Should start with @startuml");
        assertTrue(puml.contains("@enduml"), "Should contain @enduml");
    }

    // -----------------------------------------------------------------------
    // render() contains "1" --> "1" relationship
    // -----------------------------------------------------------------------

    @Test
    void render_multipleNodes_containsUsesRelationship() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.POST)
                .pathTemplate("/api/orders")
                .controllerClass("OrderController")
                .methodName("createOrder")
                .framework("Spring")
                .build();

        CallNode serviceNode = new CallNode(
                "OrderService", "save",
                CallNode.Role.SERVICE,
                false, "Order",
                List.of(), null,
                List.of(),
                List.of()
        );

        CallNode root = new CallNode(
                "OrderController", "createOrder",
                CallNode.Role.CONTROLLER,
                false, "Order",
                List.of(), null,
                List.of(),
                List.of(serviceNode)
        );

        HttpCallInfo httpCall = new HttpCallInfo("createOrder", HttpVerb.POST, "/api/orders", "Order", "OrderRequest");
        ServiceInfo angularService = new ServiceInfo("OrderService", "order.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String result = renderer.render(List.of(flow), Map.of(endpoint, root), Path.of("/tmp"));

        assertTrue(result.contains("\"1\" --> \"1\""), "Should contain cardinality relationship");
        assertTrue(result.contains("uses"), "Should contain 'uses' label");
    }

    // -----------------------------------------------------------------------
    // Regression: generic return types must not corrupt PlantUML arrows
    // (previously a global <,> → ~ replacement at PNG-export time turned
    //  ..> into ..~ and produced "Syntax Error?" images)
    // -----------------------------------------------------------------------

    @Test
    void buildPlantUmlClassSource_genericReturnTypes_passPlantUmlSyntaxCheck() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.POST)
                .pathTemplate("/api/accommodationRequests/fillNniContract")
                .controllerClass("AccommodationRequestController")
                .methodName("fillNniContract")
                .framework("Spring")
                .build();

        CallNode serviceNode = new CallNode(
                "AccommodationRequestService", "updateNniContract",
                CallNode.Role.SERVICE,
                false, "Collection<AccommodationRequest>",
                List.of("IAccommodationRequestService"), "BaseService",
                List.of(),
                List.of()
        );

        CallNode root = new CallNode(
                "AccommodationRequestController", "fillNniContract",
                CallNode.Role.CONTROLLER,
                false, "Collection<AccommodationRequestDTO>",
                List.of(), null,
                List.of(),
                List.of(serviceNode)
        );

        HttpCallInfo httpCall = new HttpCallInfo("fillNniContract", HttpVerb.POST,
                "/api/accommodationRequests/fillNniContract", "AccommodationRequestDTO", "FillNniContractDTO");
        ServiceInfo angularService = new ServiceInfo("AccommodationRequestService",
                "accommodation-request.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String puml = renderer.buildPlantUmlClassSource(
                "POST /api/accommodationRequests/fillNniContract", flow, root);

        // Arrows must survive intact
        assertTrue(puml.contains("..|>"), "Implements arrow ..|> must be intact");
        assertTrue(puml.contains("--|>"), "Extends arrow --|> must be intact");
        assertFalse(puml.contains("..~"), "Arrow must not be corrupted into ..~");
        assertFalse(puml.contains("--~"), "Arrow must not be corrupted into --~");
        // Generics escaped only inside member text
        assertTrue(puml.contains("Collection~AccommodationRequestDTO~"),
                "Generic type must be tilde-escaped in member text");

        // The PlantUML engine itself must accept the source without a syntax error
        net.sourceforge.plantuml.syntax.SyntaxResult syntax =
                net.sourceforge.plantuml.syntax.SyntaxChecker.checkSyntax(puml);
        assertFalse(syntax.isError(),
                "PlantUML reports a syntax error in:\n" + puml + "\nErrors: " + syntax.getErrors());

        // Sanity check: the checker DOES flag the old corrupted arrow form, so the
        // assertion above is meaningful.
        String corrupted = puml.replace("..|>", "..|~").replace("--|>", "--|~");
        assertTrue(net.sourceforge.plantuml.syntax.SyntaxChecker.checkSyntax(corrupted).isError(),
                "SyntaxChecker should reject the old corrupted arrow form");
    }
}
