package com.devmanchego.contextextractor.render;

import com.devmanchego.contextextractor.angular.model.HttpCallInfo;
import com.devmanchego.contextextractor.angular.model.ServiceInfo;
import com.devmanchego.contextextractor.callgraph.CallNode;
import com.devmanchego.contextextractor.callgraph.FlowCondition;
import com.devmanchego.contextextractor.java.model.EndpointInfo;
import com.devmanchego.contextextractor.java.model.HttpVerb;
import com.devmanchego.contextextractor.java.model.ScheduledJobInfo;
import com.devmanchego.contextextractor.matching.MatchedFlow;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class FlowDiagramRendererTest {

    private final FlowDiagramRenderer renderer = new FlowDiagramRenderer();

    // -----------------------------------------------------------------------
    // flowsOutputPath
    // -----------------------------------------------------------------------

    @Test
    void flowsOutputPath_derivesCorrectName() {
        Path main = Path.of("/output/api-spec.md");
        Path flows = FlowDiagramRenderer.flowsOutputPath(main);
        assertEquals("api-spec-flows.md", flows.getFileName().toString());
    }

    @Test
    void flowsOutputPath_nonMdFile_appendsSuffix() {
        Path main = Path.of("/output/report");
        Path flows = FlowDiagramRenderer.flowsOutputPath(main);
        assertEquals("report-flows.md", flows.getFileName().toString());
    }

    // -----------------------------------------------------------------------
    // render() with empty flows
    // -----------------------------------------------------------------------

    @Test
    void render_emptyFlows_returnsValidMarkdownHeader() {
        String result = renderer.render(List.of(), Map.of(), Map.of(), Path.of("/tmp"));

        assertTrue(result.contains("# Full-Stack API Flow Diagrams"));
        assertTrue(result.contains("*Generated by java-angular-fullstack-extractor*"));
    }

    // -----------------------------------------------------------------------
    // render() with a flow that has a CallNode with no conditions
    // -----------------------------------------------------------------------

    @Test
    void render_flowWithNoConditions_generatesMermaidRectangleNodes() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.GET)
                .pathTemplate("/api/orders")
                .controllerClass("OrderController")
                .methodName("getOrders")
                .framework("Spring")
                .build();

        CallNode root = new CallNode(
                "OrderController", "getOrders",
                CallNode.Role.CONTROLLER,
                false, "List",
                List.of(), null,
                List.of(),   // no conditions
                List.of()    // no callees
        );

        HttpCallInfo httpCall = new HttpCallInfo("getOrders", HttpVerb.GET, "/api/orders", "Order[]", null);
        ServiceInfo angularService = new ServiceInfo("OrderService", "order.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String result = renderer.render(List.of(flow), Map.of(endpoint, root), Map.of(), Path.of("/tmp"));

        assertTrue(result.contains("graph TD"));
        assertTrue(result.contains("GET /api/orders"));
        // Rectangle nodes use [" ... "]
        assertTrue(result.contains("[\""));
    }

    // -----------------------------------------------------------------------
    // render() with a FlowCondition (hasElse=true) generates diamond node
    // -----------------------------------------------------------------------

    @Test
    void render_flowWithCondition_generatesDiamondNode() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.POST)
                .pathTemplate("/api/orders")
                .controllerClass("OrderController")
                .methodName("createOrder")
                .framework("Spring")
                .build();

        FlowCondition condition = new FlowCondition(
                "inventoryService.hasStock(id)",
                "calls inventoryService.reserve()",
                "throws OutOfStockException",
                true
        );

        CallNode root = new CallNode(
                "OrderController", "createOrder",
                CallNode.Role.CONTROLLER,
                false, "Order",
                List.of(), null,
                List.of(condition),
                List.of()
        );

        HttpCallInfo httpCall = new HttpCallInfo("createOrder", HttpVerb.POST, "/api/orders", "Order", "OrderRequest");
        ServiceInfo angularService = new ServiceInfo("OrderService", "order.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String result = renderer.render(List.of(flow), Map.of(endpoint, root), Map.of(), Path.of("/tmp"));

        // Diamond node uses {" ... "}
        assertTrue(result.contains("{\""));
        assertTrue(result.contains("inventoryService.hasStock"));
        assertTrue(result.contains("-- Yes -->"));
        assertTrue(result.contains("-- No -->"));
    }

    // -----------------------------------------------------------------------
    // render() PlantUML output
    // -----------------------------------------------------------------------

    @Test
    void render_plantUmlOutput_containsStartAndEndMarkers() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.GET)
                .pathTemplate("/api/items")
                .controllerClass("ItemController")
                .methodName("getItems")
                .framework("Spring")
                .build();

        CallNode root = new CallNode(
                "ItemController", "getItems",
                CallNode.Role.CONTROLLER,
                false, "List",
                List.of(), null,
                List.of(),
                List.of()
        );

        HttpCallInfo httpCall = new HttpCallInfo("getItems", HttpVerb.GET, "/api/items", "Item[]", null);
        ServiceInfo angularService = new ServiceInfo("ItemService", "item.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String result = renderer.render(List.of(flow), Map.of(endpoint, root), Map.of(), Path.of("/tmp"));

        assertTrue(result.contains("@startuml"));
        assertTrue(result.contains("@enduml"));
        assertTrue(result.contains("start"));
        assertTrue(result.contains("stop"));
    }
}
