package com.devmanchego.contextextractor.render;

import com.devmanchego.contextextractor.angular.model.HttpCallInfo;
import com.devmanchego.contextextractor.angular.model.ServiceInfo;
import com.devmanchego.contextextractor.callgraph.CallNode;
import com.devmanchego.contextextractor.callgraph.FlowCondition;
import com.devmanchego.contextextractor.java.model.EndpointInfo;
import com.devmanchego.contextextractor.java.model.HttpVerb;
import com.devmanchego.contextextractor.java.model.ScheduledJobInfo;
import com.devmanchego.contextextractor.matching.MatchedFlow;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class SequenceDiagramRendererTest {

    private final SequenceDiagramRenderer renderer = new SequenceDiagramRenderer();

    // -----------------------------------------------------------------------
    // sequenceOutputPath
    // -----------------------------------------------------------------------

    @Test
    void sequenceOutputPath_derivesCorrectName() {
        Path main = Path.of("/output/api-spec.md");
        Path seq  = SequenceDiagramRenderer.sequenceOutputPath(main);
        assertEquals("api-spec-sequence.md", seq.getFileName().toString());
    }

    @Test
    void sequenceOutputPath_nonMdFile_appendsSuffix() {
        Path main = Path.of("/output/report");
        Path seq  = SequenceDiagramRenderer.sequenceOutputPath(main);
        assertEquals("report-sequence.md", seq.getFileName().toString());
    }

    // -----------------------------------------------------------------------
    // render() with empty flows
    // -----------------------------------------------------------------------

    @Test
    void render_emptyFlows_returnsValidMarkdownHeader() {
        String result = renderer.render(List.of(), Map.of(), Map.of(), Path.of("/tmp"));

        assertTrue(result.contains("# Full-Stack API Sequence Diagrams"));
        assertTrue(result.contains("*Generated by java-angular-fullstack-extractor*"));
    }

    // -----------------------------------------------------------------------
    // render() with a flow + simple CallNode (no conditions, no callees)
    // -----------------------------------------------------------------------

    @Test
    void render_flowWithSimpleCallNode_containsMermaidSequenceDiagram() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.GET)
                .pathTemplate("/api/accounts/{id}")
                .controllerClass("AccountController")
                .methodName("getAccount")
                .framework("Spring")
                .build();

        CallNode root = new CallNode(
                "AccountController", "getAccount",
                CallNode.Role.CONTROLLER,
                false, "AccountResponse",
                List.of(), null,
                List.of(),
                List.of()
        );

        HttpCallInfo httpCall = new HttpCallInfo("getAccount", HttpVerb.GET, "/api/accounts/{id}", "AccountResponse", null);
        ServiceInfo angularService = new ServiceInfo("AccountService", "account.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String result = renderer.render(List.of(flow), Map.of(endpoint, root), Map.of(), Path.of("/tmp"));

        assertTrue(result.contains("sequenceDiagram"), "Should contain sequenceDiagram keyword");
        assertTrue(result.contains("GET /api/accounts/{id}"), "Should contain the HTTP verb and path");
        assertTrue(result.contains("participant"), "Should declare participants");
    }

    // -----------------------------------------------------------------------
    // render() with a CallNode with one condition (alt block)
    // -----------------------------------------------------------------------

    @Test
    void render_flowWithCondition_containsAltBlock() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.GET)
                .pathTemplate("/api/accounts/{id}")
                .controllerClass("AccountController")
                .methodName("getAccount")
                .framework("Spring")
                .build();

        FlowCondition condition = new FlowCondition(
                "entity != null",
                "return entity",
                "throws NotFoundException",
                true
        );

        CallNode root = new CallNode(
                "AccountController", "getAccount",
                CallNode.Role.CONTROLLER,
                false, "AccountResponse",
                List.of(), null,
                List.of(condition),
                List.of()
        );

        HttpCallInfo httpCall = new HttpCallInfo("getAccount", HttpVerb.GET, "/api/accounts/{id}", "AccountResponse", null);
        ServiceInfo angularService = new ServiceInfo("AccountService", "account.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String result = renderer.render(List.of(flow), Map.of(endpoint, root), Map.of(), Path.of("/tmp"));

        assertTrue(result.contains("alt "), "Should contain alt block for condition");
        assertTrue(result.contains("entity != null"), "Should contain condition text");
    }

    // -----------------------------------------------------------------------
    // buildPlantUmlSequenceSource contains @startuml and @enduml
    // -----------------------------------------------------------------------

    @Test
    void buildPlantUmlSequenceSource_containsStartAndEndMarkers() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.GET)
                .pathTemplate("/api/accounts/{id}")
                .controllerClass("AccountController")
                .methodName("getAccount")
                .framework("Spring")
                .build();

        CallNode root = new CallNode(
                "AccountController", "getAccount",
                CallNode.Role.CONTROLLER,
                false, "AccountResponse",
                List.of(), null,
                List.of(),
                List.of()
        );

        HttpCallInfo httpCall = new HttpCallInfo("getAccount", HttpVerb.GET, "/api/accounts/{id}", "AccountResponse", null);
        ServiceInfo angularService = new ServiceInfo("AccountService", "account.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String puml = renderer.buildPlantUmlSequenceSource("GET /api/accounts/{id}", flow, root);

        assertTrue(puml.startsWith("@startuml"), "Should start with @startuml");
        assertTrue(puml.contains("@enduml"), "Should contain @enduml");
    }

    // -----------------------------------------------------------------------
    // render() PlantUML section contains -> and -->
    // -----------------------------------------------------------------------

    @Test
    void render_plantUmlSection_containsForwardAndReturnArrows() {
        EndpointInfo endpoint = EndpointInfo.builder()
                .httpVerb(HttpVerb.GET)
                .pathTemplate("/api/orders")
                .controllerClass("OrderController")
                .methodName("getOrders")
                .framework("Spring")
                .build();

        CallNode serviceNode = new CallNode(
                "OrderService", "findAll",
                CallNode.Role.SERVICE,
                false, "List",
                List.of(), null,
                List.of(),
                List.of()
        );

        CallNode root = new CallNode(
                "OrderController", "getOrders",
                CallNode.Role.CONTROLLER,
                false, "List",
                List.of(), null,
                List.of(),
                List.of(serviceNode)
        );

        HttpCallInfo httpCall = new HttpCallInfo("getOrders", HttpVerb.GET, "/api/orders", "Order[]", null);
        ServiceInfo angularService = new ServiceInfo("OrderService", "order.service.ts", List.of(httpCall));
        MatchedFlow flow = new MatchedFlow(angularService, httpCall, endpoint, null, null);

        String result = renderer.render(List.of(flow), Map.of(endpoint, root), Map.of(), Path.of("/tmp"));

        // PlantUML forward arrow
        assertTrue(result.contains(" -> "), "PlantUML section should contain forward arrows");
        // PlantUML return arrow
        assertTrue(result.contains(" --> "), "PlantUML section should contain return arrows");
    }
}
